### ISSUE TITLE
Grindelia fraxinipratensis Reveal & Barneby has wrong authorship - should be Grindelia fraxinipratensis Reveal & Beatley instead

### ISSUE THREAD

**Issue by CecSve** [gbif/backbone-feedback#144]
The issue is reported to CoL: https://github.com/CatalogueOfLife/data/issues/526

**Comment by jhnwllr** [comment]
// json for auto-checking
{
"currentName": "Grindelia fraxinipratensis Reveal & Barneby",
"proposedName": "Grindelia fraxinipratensis Reveal & Beatley"
}
[why is this here?](https://github.com/gbif/backbone-feedback/wiki/JSON-comments-for-automation-%E2%80%90-Experimental)
