### ISSUE TITLE
search for Arctophila Rupr. ex Andersson plant genus yields wrong child - Syrphid species A. bombiformis,

### ISSUE THREAD

**Issue by gbif-portal** [gbif/backbone-feedback#261]
**search for Arctophila Rupr. ex Andersson plant genus yields wrong child - Syrphid species A. bombiformis,**

https://www.gbif.org/species/2705695

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e91ebb78c94a6c7b4ca1eafc9bc77ba1:0e82ee97294bdc84a5496a151f4251058d6f3be8e4d62caacf9a306257551f6957f5b946d29413531f3176dce0ba90e8a54361e4932bb44db37dd227b0b5b2ff)
System: Chrome 100.0.4896 / Windows 10.0.0
Referer: https://www.gbif.org/species/2705695
Window size: width 1280 - height 520
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-21T15:39:39.133Z',to:'2022-04-21T15:45:39.133Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-21T15:39:39.133Z',to:'2022-04-21T15:45:39.133Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
This issue has been fixed in a previous backbone release.
