### ISSUE TITLE
Lygaeus kalmii missing/misplace in backbone

### ISSUE THREAD

**Issue by kcopas** [gbif/backbone-feedback#287]
Twitter gripe-fest on misinterpretation and misplacement of _Lygaeus kalmii:
https://twitter.com/Myrmecos/status/1483818371460304898?s=20

> Few things about @GBIF are as frustrating as its attempts to auto-correct taxonomy. 
> 
> Apparently the ubiquitous small milkweed bug, Lygaeus kalmii, spelled correctly, gets banished into the mirids as European plant bug, Orthops kalmii, and then slapped with a geography error.

See https://www.gbif.org/occurrence/2805275914

**Comment by CecSve** [comment]
This issue is fixed in a backbone update.
