### ISSUE TITLE
How to remove "artificial accepted usage for a synonym"?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/backbone-feedback#439]
**How to remove &quot;artificial accepted usage for a synonym&quot;?**

"Carex pendula" was originally published in the "Global Register of Introduced and Invasive Species - Belgium", as an accepted name for "Carex agastachys": `https://www.gbif.org/species/162644337.` We have since (March 19) reverted back to the name "Carex agastachys" (keeping the same taxonID), since "Carex pendula" is the name of another native species to Belgium

On the backbone page for  Carex pendula however, the Belgian register is still listed, with a reference to `https://www.gbif.org/species/159747346,` which states is a:

> Artificial accepted usage for a synonym if its missing to preserve the taxonomic hierarchy.

Is there a way to remove this, so the Belgian register is no longer listed as a source for Carex pendula being introduced in Belgium?

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/c0921bb5f30b2f42b40e1481de5198eb:1144fe8dd625a6d78b2405953e3ff2d775cf068f2cf8fa1596155fb190aa6a62f6efb4aec71578166703e84fd95c13b3a41b11f009ea47817d2faa0570d06920)
System: Chrome 80.0.3987 / Mac OS X 10.14.6
Referer: https://www.gbif.org/species/159747346
Window size: width 1368 - height 766
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-20T15:12:13.848Z',mode:absolute,to:'2020-03-20T15:18:13.848Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-20T15:12:13.848Z',mode:absolute,to:'2020-03-20T15:18:13.848Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by camiplata** [comment]
This issue has been adress
<img width="1504" alt="Captura de pantalla 2024-06-14 a la(s) 11 43 28 a m" src="https://github.com/gbif/backbone-feedback/assets/5700527/b2273386-74b5-4338-9288-d9677cdd4599">
