### ISSUE TITLE
Vanessa cardui kershawi should be matched to Vanessa kershawi (McCoy, 1868)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/backbone-feedback#449]
**Vanessa cardui kershawi should be matched to Vanessa kershawi (McCoy, 1868)**

These occurrences are currently matched to Vanessa cardui (Linnaeus, 1758).
However, according to one of our users, they should be matched to Vanessa kershawi (McCoy, 1868) (`https://www.gbif.org/species/5806177)` which is now its own species.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/a86d6e08b3c3cf23ed9dd1a9cb862634:9df773acf9ce89ff585361ec68ba1d62386706d66d12e98d3f907be93e4c2bb0e9ca04512f22b6957ad28a1e5851c9e1cedccc537487ca31e6b4eeff00173bdb)
System: Safari 13.0.4 / Mac OS X 10.15.2
Referer: https://www.gbif.org/occurrence/search?country=AU&issue=TAXON_MATCH_HIGHERRANK&taxon_key=4299368
Window size: width 1700 - height 979
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-15T08:58:38.250Z',mode:absolute,to:'2020-01-15T09:04:38.250Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-15T08:58:38.250Z',mode:absolute,to:'2020-01-15T09:04:38.250Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dhobern** [comment]
Seems to be correct in COL and GBIF. Not sure why this was reopened.

**Comment by ManonGros** [comment]
Thanks @dhobern, the issue was never closed, I am closing it now.
