### ISSUE TITLE
Incorrect date for name Morpho portis Hübner

### ISSUE THREAD

**Issue by ManonGros** [gbif/backbone-feedback#461]
We received a feedback message on Helpdesk concerning erroneous dates.

The user suspects that the year of "Morpho portis Hübner, 1916/24" in GBIF (https://www.gbif.org/species/5133232) should have actually been "1816/24". This year is the same as that of the Catalogue of Life (http://www.catalogueoflife.org/col/details/species/id/0a9f7b03f644fe0b51fd5d83b5d34384).  In fact, Hübner was active at the beginning of the 1800's era. For example, in GBIF there are another species names "Morpho achillaena Hübner, 1816/24" (https://www.gbif.org/species/5133328) and "Morpho aega Hübner, 1816/24" (https://www.gbif.org/species/5133366). This seems correct.

After checking it seems the original record (from the NHM) has been mis-transcribed:
https://www.nhm.ac.uk/our-science/data/lepindex/detail/?taxonno=146497
The label clearly indicates 1816/24 as the date.

**Comment by dhobern** [comment]
@ManonGros - Hi Marie - this seems to be correct now in COL and in GBIF. Was there a specific reason to reopen it?

**Comment by ManonGros** [comment]
Thanks @dhobern, the issue was never closed but you got a notification because it was transferred to a new repository. I am closing it now

**Comment by jhnwllr** [comment]
// json for auto-checking
{
"currentName": "Morpho portis Hübner, 1916/24",
"proposedName": "Morpho portis Hübner, 1816/24"
}
