### ISSUE TITLE
Missing name in backbone leads to wrong taxonomic assignment (a wasp becomes a mammal)

### ISSUE THREAD

**Issue by CecSve** [gbif/backbone-feedback#550]
Feedback from GBIF helpdesk:

> We got this one in as a bug report on MCZbase.
> 
> The error is on GBIF's part.
> 
> We are representing the higher classification as:
> 
> Animalia Arthropoda Hexapoda Insecta Pterygota Hymenoptera Apocrita Aculeata Tiphioidea Tiphiidae Aelurus
> 
> https://mczbase.mcz.harvard.edu/guid/MCZ:Ent:33413
> 
> You are replacing that with: 
> 
> Animalia Chordata Mammalia Carnivora Ailuridae Ailurus 
> 
> https://www.gbif.org/occurrence/1313441263

The species name is not part of COL nor the xRelease.

The source of the correct name can be accessed [here](https://mczbase.mcz.harvard.edu/publications/showPublication.cfm?publication_id=63772)

Please also note there seems to be an issue with the genus and generic name for the mammal, where the former is _Ailurus_ but the latter is _Aelurus_

**Comment by DianRHR** [comment]
The wasp genus [Aelurus ](https://www.checklistbank.org/dataset/6069/classification?taxonKey=x3F) is merging in the xRelease from this [source](https://www.scielo.br/j/paz/a/xdHFJ6KJbDrZS7H5fwwtvmF/?lang=en), however, its higher classification is different from the occurrences published in GBIF and in [MCZBASE](https://mczbase.mcz.harvard.edu/). 

It's current position is: Animalia | Arthropoda | Hexapoda | Insecta | Hymenoptera | Apocrita | Aculeata | Vespoidea | Thynnidae | Aelurus according to that source.

With this genus and species merged in the xRelease, the wasp won't become a mammal anymore. 

The GBIF backbone included the genus (from the same source) [properly](https://www.checklistbank.org/dataset/53147/taxon/3259195),  but the species was wrongly included below the mammal genus Ailurus.
